[package]
name = "myu"
version = "0.1.0"
authors = ["Frank de Jong <f.j.p.d.jong@student.tue.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "5.1.0"
